name: Arithmetic Operations

on:
  workflow_dispatch:
    inputs:
      num1:
        description: "First number"
        required: true
        default: "10"
      num2:
        description: "Second number"
        required: true
        default: "5"
      operation:
        description: "Choose operation (add, subtract, multiply, divide)"
        required: true
        default: "add, subtract"

jobs:
  determine-operation:
    runs-on: ubuntu-latest
    outputs:
      selected-operation: ${{ steps.set-operation.outputs.operation }}
    steps:
      - name: Set Selected Operation
        id: set-operation
        run: echo "operation=${{ github.event.inputs.operation }}" >> $GITHUB_OUTPUT

  addition:
    needs: determine-operation
    if: needs.determine-operation.outputs.selected-operation == 'add'
    runs-on: ubuntu-latest
    steps:
      - name: Perform Addition
        run: |
          num1=${{ github.event.inputs.num1 }}
          num2=${{ github.event.inputs.num2 }}
          sum=$((num1 + num2))
          echo "Sum: $sum"

  subtraction:
    needs: determine-operation
    if: needs.determine-operation.outputs.selected-operation == 'subtract'
    runs-on: ubuntu-latest
    steps:
      - name: Perform Subtraction
        run: |
          num1=${{ github.event.inputs.num1 }}
          num2=${{ github.event.inputs.num2 }}
          difference=$((num1 - num2))
          echo "Difference: $difference"

  multiplication:
    needs: determine-operation
    if: needs.determine-operation.outputs.selected-operation == 'multiply'
    runs-on: ubuntu-latest
    steps:
      - name: Perform Multiplication
        run: |
          num1=${{ github.event.inputs.num1 }}
          num2=${{ github.event.inputs.num2 }}
          product=$((num1 * num2))
          echo "Product: $product"

  division:
    needs: determine-operation
    if: needs.determine-operation.outputs.selected-operation == 'divide'
    runs-on: ubuntu-latest
    steps:
      - name: Perform Division
        run: |
          num1=${{ github.event.inputs.num1 }}
          num2=${{ github.event.inputs.num2 }}
          if [ "$num2" -ne 0 ]; then
