name: Arithmetic Operations

on:
  workflow_dispatch:
    inputs:
      num1:
        description: "First number"
        required: true
        default: "10"
      num2:
        description: "Second number"
        required: true
        default: "5"
    operation:
        description: "Choose operation (addition, subtraction, multiplication, quotient)"
        required: true
        default: "addition, "
    
  

jobs:
  addition:
    name: Addition Job
    runs-on: ubuntu-latest
    steps:
      - name: Perform Addition
        run: |
          num1=${{ github.event.inputs.num1 }}
          num2=${{ github.event.inputs.num2 }}
          sum=$((num1 + num2))
          echo "➕ Sum: $sum"

  subtraction:
    name: Subtraction Job
    runs-on: ubuntu-latest
    steps:
      - name: Perform Subtraction
        run: |
          num1=${{ github.event.inputs.num1 }}
          num2=${{ github.event.inputs.num2 }}
          difference=$((num1 - num2))
          echo "➖ Difference: $difference"
  multiplication:
    name: multiplication Job
    runs-on: ubuntu-latest
    steps:
      - name: Perform multiplication
        run: |
          num1=${{ github.event.inputs.num1 }}
          num2=${{ github.event.inputs.num2 }}
          mul=$((num1 * num2))
          echo "➖ Product: $product"
  quotient:
    name: quotient Job
    runs-on: ubuntu-latest
    steps:
      - name: Perform quotient
        run: |
          num1=${{ github.event.inputs.num1 }}
          num2=${{ github.event.inputs.num2 }}
           quotient=$((num1 / num2))
          echo "➖ quotient: $quotient"
