name: Arithmetic Operations

on:
  workflow_dispatch:
    inputs:
      num1:
        description: "First number"
        required: true
        default: "10"
      num2:
        description: "Second number"
        required: true
        default: "5"
      operation:
        description: "Choose operation (add, subtract, multiply, divide)"
        required: true
        default: "add, multiply"

jobs:
  addition:
    if: github.event.inputs.operation == 'add'
    name: Addition Job
    runs-on: ubuntu-latest
    steps:
      - name: Perform Addition
        run: |
          num1=${{ github.event.inputs.num1 }}
          num2=${{ github.event.inputs.num2 }}
          sum=$((num1 + num2))
          echo "Sum: $sum"

  subtraction:
    if: github.event.inputs.operation == 'subtract'
    name: Subtraction Job
    runs-on: ubuntu-latest
    steps:
      - name: Perform Subtraction
        run: |
          num1=${{ github.event.inputs.num1 }}
          num2=${{ github.event.inputs.num2 }}
          difference=$((num1 - num2))
          echo "Difference: $difference"

  multiplication:
    if: github.event.inputs.operation == 'multiply'
    name: Multiplication Job
    runs-on: ubuntu-latest
    steps:
      - name: Perform Multiplication
        run: |
          num1=${{ github.event.inputs.num1 }}
          num2=${{ github.event.inputs.num2 }}
          product=$((num1 * num2))
          echo "Product: $product"

  division:
    if: github.event.inputs.operation == 'divide'
    name: Division Job
    runs-on: ubuntu-latest
    steps:
      - name: Perform Division
        run: |
          num1=${{ github.event.inputs.num1 }}
          num2=${{ github.event.inputs.num2 }}
          if [ "$num2" -ne 0 ]; then
            quotient=$((num1 / num2))
            echo "Quotient: $quotient"
          else
            echo "Division by zero is not allowed"
            exit 1
          fi
