name: Issue Comment Workflow

on:
  issues:
    types: [opened]

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Post a comment on the issue
        uses: peter-evans/create-issue-comment@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: "Thanks for opening this issue! We’ll review it and get back to you soon."
