name: Scheduled Workflow

on:
  schedule:
    - cron: "*/2 * * * *" # Runs daily at 3 AM UTC

jobs:
  scheduled-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run scheduled script
        run: echo "Executing scheduled task..."
