name: Run Specific Job Example

on:
  workflow_dispatch:
    inputs:
      job_to_run:
        description: job-a
        required: true
        type: choice
        options:
          - job-a
          - job-b
          - job-c

jobs:
  job-a:
    if: ${{ github.event.inputs.job_to_run == 'job-a' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Job A"

  job-b:
    if: ${{ github.event.inputs.job_to_run == 'job-b' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Job B"

  job-c:
    if: ${{ github.event.inputs.job_to_run == 'job-c' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Job C"


