name: Modular Azure Infra Deployment

on:
  workflow_dispatch:
    inputs:
      deploy_step:
        description: "Choose the step to deploy"
        required: true
        type: choice
        options:
          - Deploy Servers in Both Regions
          - Deploy Database with Permissions
          - Deploy Server with Databases

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      selected-step: ${{ github.event.inputs.deploy_step }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

  deploy-servers-both-regions:
    needs: setup
    if: ${{ needs.setup.outputs.selected-step == 'Deploy Servers in Both Regions' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd deployments/servers-multi-region
          terraform init
          terraform apply -auto-approve

  deploy-db-with-permissions:
    needs: setup
    if: ${{ needs.setup.outputs.selected-step == 'Deploy Database with Permissions' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd deployments/database-with-permissions
          terraform init
          terraform apply -auto-approve

  deploy-server-with-db:
    needs: setup
    if: ${{ needs.setup.outputs.selected-step == 'Deploy Server with Databases' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd deployments/server-with-db
          terraform init
          terraform apply -auto-approve
