name: Modular Azure Infra Deployment

on:
  workflow_dispatch:
    inputs:
      deploy_step:
        description: "Choose the step to deploy"
        required: true
        type: choice
        options:
          - Deploy Servers in Both Regions
          - Deploy Database with Permissions
          - Deploy Server with Databases

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # Step: Deploy Servers in Both Regions
      - name: Deploy Servers in Both Regions
        if: ${{ github.event.inputs.deploy_step == 'Deploy Servers in Both Regions' }}
        run: |
          cd deployments/servers-multi-region
          terraform init
          terraform apply -auto-approve

      # Step: Deploy Database with Permissions
      - name: Deploy Database with Permissions
        if: ${{ github.event.inputs.deploy_step == 'Deploy Database with Permissions' }}
        run: |
          cd deployments/database-with-permissions
          terraform init
          terraform apply -auto-approve

      # Step: Deploy Server with Databases
      - name: Deploy Server with Databases
        if: ${{ github.event.inputs.deploy_step == 'Deploy Server with Databases' }}
        run: |
          cd deployments/server-with-db
          terraform init
          terraform apply -auto-approve

