name: Debug Workflow

on:
  push:
    branches:
      - master

jobs:
  debug-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Echo a custom message
        run: echo "🛠️ Starting debug job for commit ${{ github.sha }}"

      - name: Print Environment Variables
        run: env

      - name: Print GitHub Context
        run: echo "${{ toJson(github) }}"

      - name: Run a command that might fail
        run: |
          echo "Trying to list a nonexistent directory..."
          ls /nonexistent || echo "⚠️ ls failed, but we continue."

      - name: Continue on Error Example
        run: exit 1
        continue-on-error: true

      # Optional: SSH into the runner for live debugging (remove if not needed)
      - name: Start SSH debugging session (tmate)
        uses: mxschmitt/action-tmate@v3
        if: always()
